routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* GENERAL APP : LOGIN, REGISTRATION AND SIMPLE DASHBOARD*/
Route::group(
    [
        'domain' => 'app.' . config('app.domain'),
        'as' => 'app.'
    ],
    function () {
        Route::get('/', 'DashboardController@home')->name('home');

        Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
        Route::post('/login', 'Auth\LoginController@handleLogin')->name('login.post');
        Route::get('/registration', 'Auth\RegistrationController@showRegistrationForm')->name('registration');
        Route::post('/registration', 'Auth\RegistrationController@handleRegistration')->name('registration.post');
        Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
    }
);


/* SUPER ADMIN : SERVICE MANAGEMENT */
Route::group(
    [
        'domain' => 'admin.' . config('app.domain'),
        'middleware' => ['auth', 'app.is_admin'],
        'as' => 'admin.'
    ],
    function () {
        Route::get('/', 'Admin\DashboardController@home')->name('home');

        // @todo: Metrics, Billing/Subscription Management, etc
    }
);


/* SHOP ROUTES */
Route::group(
    [
        'domain' => '{subdomain}.' . config('app.domain'),
        'middleware' => 'shop.domain',
        'as' => 'shop.'
    ], function () {

    // Shop frontend
    Route::get('/', 'Shop\PageController@home')->name('home');

    // @todo: products, cart, checkout, etc
    // @todo: customer account, orders history, order details, settings


    // Authentication and registration
    Route::get('/login', 'Shop\Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Shop\Auth\LoginController@handleLogin')->name('login.post');
    Route::get('/registration', 'Shop\Auth\RegistrationController@showRegistrationForm')->name('registration');
    Route::post('/registration', 'Shop\Auth\RegistrationController@handleRegistration')->name('registration.post');
    Route::post('/logout', 'Shop\Auth\LoginController@logout')->name('logout');


    // SHOP MANAGEMENT
    Route::group(
        [
            'prefix' => 'admin',
            'middleware' => ['auth', 'shop.is_manager'],
            'as' => 'admin.'
        ],
        function () {

            Route::get('/', 'Shop\Admin\DashboardController@home')->name('home');

            // @todo: orders, customers, staff members, etc

        }
    );


}
);

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    public function assignUser(User $user)
    {
        $this->user_id = $user->id;
        $this->contact_name = $user->first_name . ' ' . $user->last_name;
        $this->contact_email = $user->email;
    }

    public function shop()
    {
        return $this->belongsTo('App\Shop');
    }

}

app/Manager.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Manager extends Model
{

    public function assignUser(User $user)
    {
        $this->user_id = $user->id;
        $this->contact_name = $user->first_name . ' ' . $user->last_name;
        $this->contact_email = $user->email;
    }

    public function shop()
    {
        return $this->belongsTo('App\Shop');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

}

app/Shop.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Shop extends Model
{


    /**
     * Get shop customers
     */
    public function customers()
    {
        return $this->hasMany('App\Customer');
    }

    /**
     * Get shop managers
     */
    public function managers()
    {
        return $this->hasMany('App\Manager');
    }

    /**
     * Get shop owners
     */
    public function owners()
    {
        return $this->hasMany('App\Manager')->where('is_owner', '=', '1');
    }


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function name()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function isShopManager()
    {
        return shop()->managers()->where('user_id', $this->id)->first();
    }

    public function initials()
    {
        return mb_substr($this->first_name, 0, 1) . mb_substr($this->last_name, 0, 1);
    }

    public function customers()
    {
        return $this->hasMany('App\Customer');
    }

    public function managers()
    {
        return $this->hasMany('App\Manager');
    }

    public function isAppAdmin()
    {
        return $this->is_appadmin;
    }


}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Shop;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{

    public function home()
    {
        $shops = Shop::all();
        return view('admin.dashboard', ['shops' => $shops]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');

    }

    public function home()
    {
        return view('app.dashboard', ['user' => auth()->user()]);
    }
}

app/Http/Controllers/Shop/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Shop\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function home()
    {
        return view('shop.admin.dashboard');
    }
}

app/Http/Controllers/Shop/PageController.php
<?php

namespace App\Http\Controllers\Shop;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PageController extends Controller
{
    public function home()
    {
        return view('shop.home');
    }
}

resources/views/app/dashboard.blade.php
@extends('layouts.app')

@section('title', 'Панель управления')

@section('content')

    <div class="row no-margin mb-2 justify-content-between">


        <div class="col-12 d-flex justify-content-between">
            <a href="{{ route('app.home') }}" class="btn btn-outline-secondary" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <i class="fas fa-power-off"></i> Logout
            </a>
            <form id="logout-form" action="{{ route('app.logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>

            <a href="{{ route('app.registration') }}" class="btn btn-primary">
                Create new shop
            </a>
            @if($user->isAppAdmin())
                <a href="{{ route('admin.home') }}" class="btn btn-outline-primary">
                    Go to App Control Panel &rarr;
                </a>
            @endif
        </div>
    </div>

    @if($user->managers()->count() > 0)
    <div class="card mb-5">
        <div class="card-body">
            <h5 class="card-title">Your shops</h5>
            <div class="list-group">
                @foreach($user->managers()->get() as $manager)
                <a href="{{ route('shop.home', ['domain' => $manager->shop->domain]) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ $manager->shop->company_name }}</h5>
                        <small>{{ $manager->is_owner ? 'Owner' : 'Manager' }}</small>
                    </div>
                    <small>http://{{ $manager->shop->domain }}.{{ config('app.domain') }}</small>
                </a>
                @endforeach
            </div>
        </div>
    </div>
    @endif

    @if($user->customers()->count() > 0)
        <div class="card mb-5">
            <div class="card-body">
                <h5 class="card-title">Customer</h5>
                <div class="list-group">
                    @foreach($user->customers()->get() as $customer)
                        <a href="{{ route('shop.home', ['domain' => $customer->shop->domain]) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{ $customer->shop->company_name }}</h5>
                            </div>
                            <small>http://{{ $customer->shop->domain }}.{{ config('app.domain') }}</small>
                        </a>
                    @endforeach
                </div>
            </div>
        </div>
    @endif

@endsection

resources/views/app/login.blade.php
@extends('layouts.app')

@section('title', 'Авторизация')

@section('content')

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Authentication</h4>
            <form method="post" action="{{ route('app.login.post') }}">
                {{ csrf_field() }}
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-group">
                    <label for="email">E-Mail</label>
                    <input id="email" name="email" type="email" value="{{ old('email') }}"  type="email" class="form-control" name="email" placeholder="john.doe@example.com" required autofocus>
                </div>

                <div class="form-group">
                    <label for="password">Password
                    </label>
                    <input id="password" name="password" type="password" class="form-control" name="password" placeholder="password" required>
                    <div class="text-right">
                        <a href="#" class="small">
                            Forgot your password?
                        </a>
                    </div>
                </div>

                <div class="form-group">
                    <label>
                        <input type="checkbox" name="is_remember" value="1"> Remember me
                    </label>
                </div>

                <div class="form-group no-margin">
                    <button type="submit" class="btn btn-primary btn-block">
                        Login
                    </button>
                </div>
                <div class="text-center mt-3 small">
                    Do not have an account? <a href="{{ route('app.registration') }}">Create a new one</a>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/app/registration.blade.php
@extends('layouts.app')

@section('title', 'Регистрация')

@section('content')

    @auth
    <div class="form-group no-margin mb-2 text-left">
        <a href="{{ route('app.home') }}" class="btn btn-outline-primary">
            &laquo; Cancel
        </a>
    </div>
    @endauth

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Registration</h4>
            <form method="post" action="{{ route('app.registration.post') }}">
                {{ csrf_field() }}
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-group">
                    <label for="company_name">Shop Name</label>
                    <input id="company_name" name="company_name" value="{{ old('company_name') }}" type="text" class="form-control" placeholder='Acme Inc.' required autofocus>
                </div>
                <div class="form-group">
                    <label for="company_domain">Shop Domain</label>
                    <div class="input-group">
                        <input id="company_domain" name="company_domain" value="{{ old('company_domain') }}" type="text" class="form-control" placeholder="acme" aria-label="Comapny domain" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <span class="input-group-text" id="basic-addon2">.{{ config('app.domain') }}</span>
                        </div>
                    </div>
                </div>

                @guest
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="first_name">First Name</label>
                        <input id="first_name" name="first_name" value="{{ old('first_name') }}" type="text" class="form-control" placeholder="John">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="last_name">Last Name</label>
                        <input id="last_name" name="last_name" value="{{ old('last_name') }}" type="text" class="form-control" placeholder="Doe">
                    </div>
                </div>

                <div class="form-group">
                    <label for="email">E-Mail</label>
                    <input id="email" name="email" type="email" value="{{ old('email') }}" class="form-control" placeholder="john.doe@example.com" required>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="password">Password
                        </label>
                        <input id="password" name="password" type="password" class="form-control" placeholder="Password" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="password_confirmation">Confirm Password
                        </label>
                        <input id="password_confirmation" name="password_confirmation" type="password" class="form-control" placeholder="Confirm Password" required>
                    </div>
                </div>
                @endguest

                <div class="form-group no-margin">
                    <button type="submit" class="btn btn-primary btn-block">
                        Create new shop
                    </button>
                </div>
                <div class="text-center mt-3 small">
                    Already have an account? <a href="{{ route('app.login') }}">Login here</a>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Fontawesome -->
    <script defer src="//use.fontawesome.com/releases/v5.0.9/js/all.js"></script>


    <link rel="stylesheet" href="{{ mix('app_admin/css/app.css') }}">

    <title>@yield('title', 'Demo') - {{ config('app.name') }}</title>
</head>
<body>
<div class="sidebar-main">
    <div class="sidebar-header">
        <a href="{{ domain_route('shop.admin.home') }}" title="{{ config('app.name') }}"><img src="{{ asset('shop/admin/img/logo.png') }}"></a>
    </div>
    <ul class="sidebar-nav">
        <li class="nav-item active"><a class="item" href="#" title="Dashboard"><i class="icon fas fa-home"></i></a></li>
        <li class="nav-item"><a class="item" href="#" title="Settings"><i class="icon fas fa-cog"></i></a></li>
        <li class="nav-item divider"></li>
        <li class="nav-item filled reverse"><a class="item" href="{{ domain_route('shop.home') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" title="Logout"><i class="icon fas fa-power-off"></i></a></li>
    </ul>
</div>

<nav class="navbar navbar-expand-lg navbar-light justify-content-between">
    <a class="navbar-brand" href="{{ route('admin.home') }}">App Control Panel</a>



    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
        <ul class="navbar-nav mr-3">
            <li class="nav-item active">
                <a class="nav-link" href="#">Dashboard <span class="sr-only">(current)</span></a>
            </li>
        </ul>





        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown dropdown-image">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span data-letters="{{ $user->initials() }}"> {{ $user->name() }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ route('admin.home') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<div class="container-fluid">

    @yield('content')




</div>


<script src="{{ mix('app_admin/js/app.js') }}"></script>
<form id="logout-form" action="{{ route('app.logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Fontawesome -->
    <script defer src="//use.fontawesome.com/releases/v5.0.9/js/all.js"></script>


    <link rel="stylesheet" href="{{ mix('app/css/app.css') }}">

    <title>@yield('title', 'Demo') - {{ config('app.name') }}</title>
</head>
<body class="is-no-margin">


<div class="container-fluid pb-5">

    <div class="row justify-content-md-center">
        <div class="card-wrapper col-4 mt-5">
            <div class="brand text-center mb-3">
                <a href="{{ route('app.home') }}" title="{{ config('app.name') }}"><img src="{{ asset('app/img/logo.png') }}"></a>
            </div>
            @yield('content')

            <footer class="footer mt-3">
                <div class="container-fluid">
                    <div class="footer-content text-center small">
                        <span class="text-muted">
                            &copy; {{ date('Y') }} All rights reserved.<br>
                             <a href="{{ config('app.url') }}" title="{{ config('app.name') }}" target="_blank">{{ config('app.name') }}</a> &mdash; Demo Application.<br>
                            Built on top of <a href="https://graindashboard.com" title="Grain Dashboard" target="_blank">Grain Dashboard</a> . Developed by <a href="https://digitalwheat.com" title="DigitalWheat" target="_blank">DigitalWheat</a>.
                        </span>
                    </div>
                </div>
            </footer>
        </div>
    </div>



</div>

<script src="{{ mix('app/js/app.js') }}"></script>

</body>
</html>

resources/views/layouts/shop.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Fontawesome -->
    <script defer src="//use.fontawesome.com/releases/v5.0.9/js/all.js"></script>


    <link rel="stylesheet" href="{{ mix('shop/css/app.css') }}">

    <title>@yield('title', 'Demo') - {{ config('app.name') }}</title>
</head>
<body>

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
        <a class="navbar-brand" href="{{ domain_route('shop.home') }}">{{ shop()->company_name }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarMain">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ domain_route('shop.home') }}">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li><a class="nav-link" href="#"><i class="fas fa-shopping-cart"></i></a></li>
                @guest
                    <li><a class="nav-link" href="{{ domain_route('shop.login') }}">Login</a></li>
                    <li><a class="nav-link" href="{{ domain_route('shop.registration') }}">Registration</a></li>
                @else
                    <li class="nav-item dropdown dropdown-image">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ $user->name() }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            @if($user->isShopManager())
                                <a class="dropdown-item" href="{{ domain_route('shop.admin.home') }}">Shop Dashboard</a>
                            @else
                            <a class="dropdown-item" href="#">Settings</a>
                            <a class="dropdown-item" href="#">My Orders</a>
                            @endif
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item"  href="{{ domain_route('shop.home') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fas fa-power-off"></i> Logout</a>
                            <form id="logout-form" action="{{ domain_route('shop.logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </nav>


    @yield('content')




</div>

<script src="{{ mix('shop/js/app.js') }}"></script>

</body>
</html>

resources/views/layouts/shop_admin.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Fontawesome -->
    <script defer src="//use.fontawesome.com/releases/v5.0.9/js/all.js"></script>


    <link rel="stylesheet" href="{{ mix('shop/admin/css/app.css') }}">

    <title>@yield('title', 'Demo') - {{ config('app.name') }}</title>
</head>
<body>
<div class="sidebar-main">
    <div class="sidebar-header">
        <a href="{{ domain_route('shop.admin.home') }}" title="{{ config('app.name') }}"><img src="{{ asset('shop/admin/img/logo.png') }}"></a>
    </div>
    <ul class="sidebar-nav">
        <li class="nav-item active"><a class="item" href="#" title="Dashboard"><i class="icon fas fa-home"></i></a></li>
        <li class="nav-item"><a class="item" href="#" title="Orders"><i class="icon far fa-file-alt"></i></a></li>
        <li class="nav-item"><a class="item" href="#" title="Customers"><i class="icon fas fa-users"></i></a></li>
        <li class="nav-item"><a class="item" href="#" title="Settings"><i class="icon fas fa-cog"></i></a></li>
        <li class="nav-item divider"></li>
        <li class="nav-item filled reverse"><a class="item" href="{{ domain_route('shop.home') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" title="Logout"><i class="icon fas fa-power-off"></i></a></li>
    </ul>
</div>

<nav class="navbar navbar-expand-lg navbar-light justify-content-between">
    <a class="navbar-brand" href="{{ domain_route('shop.admin.home') }}">{{ shop()->company_name }}</a>



    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
        <ul class="navbar-nav mr-3">
            <li class="nav-item active">
                <a class="nav-link" href="#">Dashboard <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Orders</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Customers</a>
            </li>
        </ul>

        <div class="mr-auto">
            <a class="btn btn-outline-secondary btn-sm" target="_blank" href="{{ domain_route('shop.home') }}">Go to storefront &rarr;</a>
        </div>




        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown dropdown-image">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span data-letters="{{ $user->initials() }}"> {{ $user->name() }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ domain_route('shop.home') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<div class="container-fluid">

    @yield('content')




</div>


<script src="{{ mix('shop/admin/js/app.js') }}"></script>
<form id="logout-form" action="{{ domain_route('shop.logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>
</body>
</html>

resources/views/shop/admin/dashboard.blade.php
@extends('layouts.shop_admin')

@section('title', 'Shop Dashboard')

@section('content')

    <div class="page-header">
        <div class="page-title">Shop Dashboard</div>
    </div>



@endsection

resources/views/shop/login.blade.php
@extends('layouts.shop')

@section('title', 'Authentication')

@section('content')

    <div class="row justify-content-center mt-5">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Authentication</div>

                <div class="card-body">
                    <form method="POST" action="{{ domain_route('shop.login.post') }}">
                        {{ csrf_field() }}
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group row">
                            <label for="email" class="col-sm-4 col-form-label text-md-right">E-Mail</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" placeholder="john.doe@example.com" value="{{ old('email') }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" placeholder="Password" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="is_remember" value="1"> Remember me
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>

                                <a class="btn btn-link" href="#">
                                    Forgot your password?
                                </a>
                            </div>
                        </div>
                        <div class="form-group row mb-0 mt-2">
                            <div class="col-md-8 offset-md-4 text-muted small">
                                Do not have an account? <a class="" href="{{ domain_route('shop.registration') }}">Create a new one</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection